const express = require('express');
const router = express.Router();
const uuid = require('uuid'); //get autogenerated ids
const customers = require('../data/customersData')

//get all customers
router.get('/', (req, res) => {
    res.json(customers);
})

//get single customer
router.get('/:id', (req, res, next) => {
    const customer = customers.find((item) => item.id == req.params.id);
    if(customer) res.json(customer);
    else next();
})

//create a customer
router.post('/', (req, res) => {
    const newCustomer = {
        id: uuid.v4(),
        name: req.body.name,
        surname: req.body.surname,
        email: req.body.email
    }

    for(let key of Object.keys(newCustomer)) {
        if(!newCustomer[key]) {
            res.status(400).json({ msg: 'Make sure to enter name, surname and email'});
        }
    }

    customers.push(newCustomer);

    res.json(customers);
})

//post single customer
router.put('/:id', (req, res) => {
    const found = customers.some(customer => customer.id === parseInt(req.params.id));
    if(found) {
        const updatedCustomer = req.body;
        customers.forEach(element => {
            if(element.id === parseInt(req.params.id)) {
                element.id = updatedCustomer.id ? updatedCustomer.id : element.id;
                element.name = updatedCustomer.name ? updatedCustomer.name : element.name;
                element.surname = updatedCustomer.surname ? updatedCustomer.surname : element.surname;
                element.email = updatedCustomer.email ? updatedCustomer.email : element.email;

                res.json({ msg: `Updated customer`, element })
            }
        });
    } else {
        res.status(400).json({ msg: `Customer not found with id of ${req.params.id}` });
    }
})

//delete a customer
router.delete('/:id', (req, res) =>{
    const found = customers.find(customer => customer.id === parseInt(req.params.id));

    if(found) {
        res.json({ msg: 'Customer deleted', customers: customers.filter(customer => customer.id !== req.params.id)})
    } else {
        res.json({ msg: `Customer not found with id of ${req.params.id}` })
    }
})

//----------------------------------------------------------export
module.exports = router;